# Generated by Django 3.0.8 on 2020-07-23 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200722_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imgURL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Womens Clothes', 'Womens Clothes'), ('Jewlelery', 'Jewlelery'), ('Mens Clothes', 'Mens Clothes'), ('Tech', 'Tech'), ('Toys', 'Toys'), ('Other', 'Other')], max_length=16),
        ),
    ]
