# Generated by Django 3.0.8 on 2020-07-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200723_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Fashion', 'Fashion'), ('Jewlelery', 'Jewlelery'), ('Electronics', 'Electronics'), ('Toys', 'Toys'), ('Other', 'Other')], max_length=16),
        ),
    ]
