# Generated by Django 3.0.8 on 2020-07-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200724_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Watchlist',
        ),
    ]
